# ---
# - name: "Creates directory for backend"
#   file:
#     path: ~/backend
#     state: directory

# - name: copy archived file into remote server
#   copy:
#     src: ~/artifact.tar.gz
#     dest: /home/ubuntu/backend/artifact.tar.gz
#     mode: "0777"
#     backup: yes

# - name: "Installing Node Dependencies"
#   shell: |
#     cd ~/backend
#     tar -xvzf artifact.tar.gz
#     npm install -f
# - name: "Executing Node app with PM2"
#   shell: |
#     cd ~/backend
#     pm2 start npm -- start -f
#     pm2 list
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#     pm2 save

---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start